# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8406a470bf75097e84ac951c5336b4abfc4a0d20fca9a434431845650516a6aa8ae4e4d71f8de2fd0c1fe5c11a976c47076874a5a01290d9ea7e82361c5bd34e

test:
  secret_key_base: 15d4c41bc8fa2cbb9f28ba621245595b3c4d9e74c11571c6a4e8098ca91a9c77da4e01e83f6a1929aa53d49d3f9e1640168a5530b2fa800c8ed725c6f03c35d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
